interceptors:
# Configure your interceptors
#  - name: loggingInterceptor
#    pluginClass: io.conduktor.example.loggerinterceptor.LoggerInterceptorPlugin
#    timeoutMs: 30000 #optional, default timeoutMs = 30s
#    priority: 100
#    config:
#      - key: "loggingStyle"
#        value: "obiWan"