version: '3'
services:
  gateway:
    image: "docker.io/conduktor/conduktor-gateway-oss:latest"
    depends_on:
      - kafka
    ports:
      - "6969:6969"
      - "8888:8888"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CONFIGURATION_FILE_PATH: /config/application.yaml
    volumes:
      - type: bind
        source: ./application.yaml
        target: /config/application.yaml
      - type: bind
        source: ./interceptors
        target: /app/plugins
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    restart: always
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-kafka:latest"
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_BROKER_ID: 1
